# Generated by Django 3.1.5 on 2021-02-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hey! Here I am in DjangoBLOG'),
        ),
    ]
